/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-07-23 08:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1482133440000L));
    _jspx_dependants.put("jar:file:/D:/0.swStudy/4.web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Coin/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>coINsight</title>\r\n");
      out.write("<meta charset=\"euc-kr\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<!--[if lte IE 8]><script src=\"assets/js/ie/html5shiv.js\"></script><![endif]-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"assets/css/ie9.css\" /><![endif]-->\r\n");
      out.write("<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"assets/css/ie8.css\" /><![endif]-->\r\n");
      out.write("<link href=\"https://cdn.rawgit.com/YJSoft/Webfonts/0.1/BM_HANNA.css\"  rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- <link href=\"https://cdn.rawgit.com/singihae/Webfonts/master/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script>\r\n");
      out.write("@import url('https://cdn.rawgit.com/singihae/Webfonts/master/style.css');\r\n");
      out.write("</script> -->\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*  * {font-family:'BM HANNA','배달의민족 한나 ' !important, sans-serif; }  */\r\n");
      out.write("table { font-family:'BM HANNA'; }\r\n");
      out.write(".table-wrapper { font-family:'BM HANNA'; }\r\n");
      out.write("th {text-align:center;}\r\n");
      out.write("tr:nth-child(even){background-color: rgba(183, 191, 233, 0.34);}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!-- Wrapper -->\r\n");
      out.write("   <div id=\"wrapper\">\r\n");
      out.write("      <!-- 실시간 코인 값 받아오는 로직 -->\r\n");
      out.write("      <!-- <div id=\"BTC\"></div> -->\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("               var btc_c,eth_c,dash_c,ltc_c,etc_c,xrp_c,btc_c1,eth_c1,dash_c1,ltc_c1,etc_c1,xrp_c1;\r\n");
      out.write("               var pbtc_c,peth_c,pdash_c,pltc_c,petc_c,pxrp_c,obj,tempval;\r\n");
      out.write("            \r\n");
      out.write("               function number_format(num){\r\n");
      out.write("            \t\treturn String(num).replace(/(\\d)(?=(?:\\d{3})+(?!\\d))/g, '$1,');\r\n");
      out.write("            \t}\r\n");
      out.write("               \r\n");
      out.write("              var currency;\r\n");
      out.write("            \t window.onload = function(){\r\n");
      out.write("            \t\tgetCurrencyData();\r\n");
      out.write("            \t}\r\n");
      out.write("             function getCurrencyData() {\r\n");
      out.write("                   $.ajax({\r\n");
      out.write("                   url : \"http://api.fixer.io/latest?base=USD\",\r\n");
      out.write("                   dataType : \"html\",\r\n");
      out.write("                   method : \"GET\",\r\n");
      out.write("                   success : function(result) {\r\n");
      out.write("                      result = result.replace(/(\\s*)/g, \"\");         \r\n");
      out.write("                      obj = eval(\"(\" + result + \")\");\r\n");
      out.write("                      currency = obj.rates.KRW;\r\n");
      out.write("                      $(\"#krw\").text(currency);\r\n");
      out.write("                      $(\"#krw2\").text(currency);\r\n");
      out.write("                   }\r\n");
      out.write("               });\r\n");
      out.write("             }\r\n");
      out.write("            \t\t   \r\n");
      out.write("               function myFun() {\r\n");
      out.write("               $.ajax({\r\n");
      out.write("               url : \"bithumbUrl.jsp\",\r\n");
      out.write("               dataType : \"html\",\r\n");
      out.write("               method : \"GET\",\r\n");
      out.write("               success : function(result) {\r\n");
      out.write("                  result = result.replace(/(\\s*)/g, \"\");         \r\n");
      out.write("                  obj = eval(\"(\" + result + \")\");\r\n");
      out.write("                  if (obj.message == null){\r\n");
      out.write("                  btc_c = obj.data.BTC.closing_price;   \r\n");
      out.write("                  eth_c = obj.data.ETH.closing_price;\r\n");
      out.write("                  dash_c = obj.data.DASH.closing_price;\r\n");
      out.write("                  ltc_c = obj.data.LTC.closing_price;\r\n");
      out.write("                  etc_c = obj.data.ETC.closing_price;\r\n");
      out.write("                  xrp_c = obj.data.XRP.closing_price;\r\n");
      out.write("                  BTC_bper = ((btc_c-obj.data.BTC.opening_price)/btc_c*100).toFixed(2);\r\n");
      out.write("                  if(BTC_bper > 0)\r\n");
      out.write("                \t $(\"#BTC\").html(number_format(btc_c) +\"<div style='float:right; color:#9beb97;'>(\" + BTC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else \r\n");
      out.write("                \t $(\"#BTC\").html(number_format(btc_c) +\"<div style='float:right; color:red;'>(\" + BTC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  ETH_bper = ((eth_c-obj.data.ETH.opening_price)/eth_c*100).toFixed(2);\r\n");
      out.write("                  if(ETH_bper > 0)\r\n");
      out.write("                 \t $(\"#ETH\").html(number_format(eth_c) +\"<div style='float:right; color:#9beb97;'>(\" + ETH_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else\r\n");
      out.write("                \t $(\"#ETH\").html(number_format(eth_c) +\"<div style='float:right; color:red;'>(\" + ETH_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  DASH_bper = ((dash_c-obj.data.DASH.opening_price)/dash_c*100).toFixed(2);\r\n");
      out.write("                  if(DASH_bper > 0)\r\n");
      out.write("                \t  $(\"#DASH\").html(number_format(dash_c) +\"<div style='float:right; color:#9beb97;'>(\" + DASH_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else\r\n");
      out.write("                 \t $(\"#DASH\").html(number_format(dash_c) +\"<div style='float:right; color:red;'>(\" + DASH_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  LTC_bper = ((ltc_c-obj.data.LTC.opening_price)/ltc_c*100).toFixed(2);\r\n");
      out.write("                  if(LTC_bper > 0)\r\n");
      out.write("                \t  $(\"#LTC\").html(number_format(ltc_c) +\"<div style='float:right; color:#9beb97;'>(\" + LTC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else\r\n");
      out.write("                 \t $(\"#LTC\").html(number_format(ltc_c) +\"<div style='float:right; color:red;'>(\" + LTC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  ETC_bper = ((etc_c-obj.data.ETC.opening_price)/etc_c*100).toFixed(2);\r\n");
      out.write("                  if(ETC_bper > 0)\r\n");
      out.write("                \t  $(\"#ETC\").html(number_format(etc_c) +\"<div style='float:right; color:#9beb97;'>(\" + ETC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else\r\n");
      out.write("                 \t $(\"#ETC\").html(number_format(etc_c) +\"<div style='float:right; color:red;'>(\" + ETC_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  XRP_bper = ((xrp_c-obj.data.XRP.opening_price)/xrp_c*100).toFixed(2);\r\n");
      out.write("                  if(XRP_bper > 0)\r\n");
      out.write("                \t  $(\"#XRP\").html(number_format(xrp_c) +\"<div style='float:right; color:#9beb97;'>(\" + XRP_bper + \"%\" + \")</div>\");\r\n");
      out.write("                  else\r\n");
      out.write("                 \t $(\"#XRP\").html(number_format(xrp_c) +\"<div style='float:right; color:red;'>(\" + XRP_bper + \"%\" + \")</div>\");\r\n");
      out.write("                 \r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            });\r\n");
      out.write("         }\r\n");
      out.write("            //폴로닉스 api 받아오는 함수\r\n");
      out.write("            function myFun2() {\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                  url : \"poloniexUrl.jsp\",\r\n");
      out.write("                  dataType : \"html\",\r\n");
      out.write("                  method : \"GET\",\r\n");
      out.write("                  success : function(result2) {\r\n");
      out.write("                     result2 = result2.replace(/(\\s*)/g, \"\");               \r\n");
      out.write("                     obj = eval(\"(\" + result2 + \")\");\r\n");
      out.write("                     pbtc_c = parseInt(obj.USDT_BTC.last*currency);\r\n");
      out.write("                     peth_c = parseInt(obj.USDT_ETH.last*currency);\r\n");
      out.write("                     pdash_c = parseInt(obj.USDT_DASH.last*currency);\r\n");
      out.write("                     pltc_c = parseInt(obj.USDT_LTC.last*currency);\r\n");
      out.write("                     petc_c = parseInt(obj.USDT_ETC.last*currency);\r\n");
      out.write("                     pxrp_c = parseInt(obj.USDT_XRP.last*currency);\r\n");
      out.write("                     BTC_per = (obj.USDT_BTC.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(BTC_per > 0)\r\n");
      out.write("                    \t $(\"#PBTC\").html(number_format(pbtc_c) +\"<div style='float:right; color:#9beb97;'>(\" + BTC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else \r\n");
      out.write("                    \t $(\"#PBTC\").html(number_format(pbtc_c) +\"<div style='float:right; color:red;'>(\" + BTC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     ETH_per = (obj.USDT_ETH.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(ETH_per > 0)\r\n");
      out.write("                    \t $(\"#PETH\").html(number_format(peth_c)+\"<div style='float:right; color:#9beb97;'>(\" + ETH_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else\r\n");
      out.write("                    \t $(\"#PETH\").html(number_format(peth_c)+\"<div style='float:right; color:red;'>(\" + ETH_per + \"%\" + \")</div>\");\r\n");
      out.write("                     DASH_per = (obj.USDT_DASH.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(DASH_per > 0)\r\n");
      out.write("                    \t $(\"#PDASH\").html(number_format(pdash_c)+\"<div style='float:right; color:#9beb97;'>(\" + DASH_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else\r\n");
      out.write("                    \t $(\"#PDASH\").html(number_format(pdash_c)+\"<div style='float:right; color:red;'>(\" + DASH_per + \"%\" + \")</div>\");\r\n");
      out.write("                     LTC_per = (obj.USDT_LTC.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(LTC_per > 0)\r\n");
      out.write("                    \t $(\"#PLTC\").html(number_format(pltc_c)+\"<div style='float:right; color:#9beb97;'>(\" + LTC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else\r\n");
      out.write("                    \t $(\"#PLTC\").html(number_format(pltc_c)+\"<div style='float:right; color:red;'>(\" + LTC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     ETC_per = (obj.USDT_ETC.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(ETC_per > 0)\r\n");
      out.write("                    \t $(\"#PETC\").html(number_format(petc_c)+\"<div style='float:right; color:#9beb97;'>(\" + ETC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else\r\n");
      out.write("                    \t $(\"#PETC\").html(number_format(petc_c)+\"<div style='float:right; color:red;'>(\" + ETC_per + \"%\" + \")</div>\");\r\n");
      out.write("                     XRP_per = (obj.USDT_XRP.percentChange*100).toFixed(2);\r\n");
      out.write("                     if(XRP_per > 0)\r\n");
      out.write("                    \t $(\"#PXRP\").html(number_format(pxrp_c)+\"<div style='float:right; color:#9beb97;'>(\" + XRP_per + \"%\" + \")</div>\");\r\n");
      out.write("                     else\r\n");
      out.write("                    \t $(\"#PXRP\").html(number_format(pxrp_c)+\"<div style='float:right; color:red;'>(\" + XRP_per + \"%\" + \")</div>\");\r\n");
      out.write("                     if(btc_c != null && pbtc_c != null){\r\n");
      out.write("\t                     if(btc_c>pbtc_c){\r\n");
      out.write("\t                     tempval = (btc_c - pbtc_c)/btc_c*100;\r\n");
      out.write("\t                     $(\"#BTC_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (pbtc_c-btc_c)/btc_c*100;\r\n");
      out.write("\t                     $(\"#BTC_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'>  <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     }\r\n");
      out.write("                     }\r\n");
      out.write("                     if(eth_c != null && peth_c != null){\r\n");
      out.write("\t                     if(eth_c>peth_c){\r\n");
      out.write("\t                     tempval = (eth_c - peth_c)/eth_c*100;\r\n");
      out.write("\t                     $(\"#ETH_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (peth_c-eth_c)/eth_c*100;\r\n");
      out.write("\t                     $(\"#ETH_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     }\r\n");
      out.write("                     }\r\n");
      out.write("                     if(dash_c != null && pdash_c != null){\r\n");
      out.write("\t                     if(dash_c>pdash_c){\r\n");
      out.write("\t                     tempval = (dash_c - pdash_c)/dash_c*100;\r\n");
      out.write("\t                     $(\"#DASH_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (pdash_c-dash_c)/dash_c*100;\r\n");
      out.write("\t                     $(\"#DASH_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     }\r\n");
      out.write("                     }\r\n");
      out.write("                     if(ltc_c != null && pltc_c != null){\r\n");
      out.write("\t                     if(ltc_c>pltc_c){\r\n");
      out.write("\t                     tempval = (ltc_c - pltc_c)/ltc_c*100;\r\n");
      out.write("\t                     $(\"#LTC_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (pltc_c-ltc_c)/ltc_c*100;\r\n");
      out.write("\t                     $(\"#LTC_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     }\r\n");
      out.write("                     }\r\n");
      out.write("                     if(etc_c != null && petc_c != null){\r\n");
      out.write("\t                     if(etc_c>petc_c){\r\n");
      out.write("\t                   \t tempval = (etc_c - petc_c)/etc_c*100;\r\n");
      out.write("\t                     $(\"#ETC_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (petc_c-etc_c)/etc_c*100;\r\n");
      out.write("\t                     $(\"#ETC_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     }\r\n");
      out.write("                     }\r\n");
      out.write("                     if(xrp_c != null && pxrp_c != null){\r\n");
      out.write("\t                     if(xrp_c>pxrp_c){\r\n");
      out.write("\t                     tempval = (xrp_c - pxrp_c)/xrp_c*100;\r\n");
      out.write("\t                     $(\"#XRP_p\").html(tempval.toFixed(2) + \"%\"+ \"    (<img src='images/logo_bithumb.png' width='80' height='28' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");   \r\n");
      out.write("\t                     }\r\n");
      out.write("\t                     else{\r\n");
      out.write("\t                     tempval = (pxrp_c-xrp_c)/xrp_c*100;\r\n");
      out.write("\t                     $(\"#XRP_p\").html(tempval.toFixed(2) + \"%\"+ \"   (<img src='images/poloniex.png' width='80' height='19' style='padding-top:5px;'> <i class='fa fa-arrow-up' style='font-size:26px; color:#9beb97;'></i>)\");\r\n");
      out.write("\t                     } \r\n");
      out.write("                     }\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("            }\r\n");
      out.write("            function myFunction2() {\r\n");
      out.write("               myVar = setInterval(myFun2, 1000);\r\n");
      out.write("               \r\n");
      out.write("            }\r\n");
      out.write("            function myFunction() {\r\n");
      out.write("            myVar = setInterval(myFun, 1000);\r\n");
      out.write("         }\r\n");
      out.write("            myFunction();\r\n");
      out.write("            myFunction2();\r\n");
      out.write("      </script>\r\n");
      out.write("      <!-- ---------------------------------- -->\r\n");
      out.write("      <!-- Header -->\r\n");
      out.write("      <header id=\"header\" class=\"alt\">\r\n");
      out.write("         <a href=\"index.jsp\" class=\"logo\"><img src=\"images/coinsight.png\"\r\n");
      out.write("            style=\"width: 260px; height: 60px;\"></a>\r\n");
      out.write("         <nav>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <a href=\"#menu\">Menu</a>\r\n");
      out.write("         </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Menu -->\r\n");
      out.write("      <nav id=\"menu\">\r\n");
      out.write("\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"coin?command=wallet\">Wallet</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp#hidden\">Real Time Chart</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp#one\">Coin Graph</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"actions vertical\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("      <!-- Banner -->\r\n");
      out.write("      <section id=\"banner\" class=\"major\" style=\"height: 700px;\">\r\n");
      out.write("         <div class=\"inner\">\r\n");
      out.write("            <header class=\"major\">\r\n");
      out.write("               <h1>\r\n");
      out.write("                  <!--   안녕하세요, <strong>coINsight</strong>입니다. -->\r\n");
      out.write("                  <img src=\"images/anigif.gif\">\r\n");
      out.write("               </h1>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("               <p>\r\n");
      out.write("                  coINsight란 coin(코인) + sight(시야)를 통해 파생된 단어로서, <br> 더불어 co(함께)\r\n");
      out.write("                  + insight(통찰력) 이라는 뜻을 가지고 있습니다.<br> coINsight는 가상화폐의 다양한 종류\r\n");
      out.write("                  별, 그리고 거래소 별 시세 비교를 한 눈에 쉽게 그래프 차트로 제공합니다.<br> 또한 사용자가 구매한\r\n");
      out.write("                  가상화폐의 현재 시세와 비교하여 수익률을 계산하는 기능을 추가로 제공합니다.<br> coINsight와 함께\r\n");
      out.write("                  가상화폐 거래에서 더욱 뛰어난 통찰력으로 높은 수익 창출을 경험해보세요. <br>\r\n");
      out.write("               </p>\r\n");
      out.write("\r\n");
      out.write("               <ul class=\"actions\">\r\n");
      out.write("                  <li><a href=\"#hihi\" class=\"button next scrolly\">시작하기</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\t <div id=\"hidden\" style=\"height:50px;\"></div>\r\n");
      out.write("      <div id=\"hihi\" style=\"height: 600px\">\r\n");
      out.write("         <!-- Table -->\r\n");
      out.write("\r\n");
      out.write("         <div style=\"width: 10%; margin: 0 auto;\">\r\n");
      out.write("            <!-- <button\r\n");
      out.write("               style=\"width: 100%; height: 50px; background-color: white; color: navy;\">\r\n");
      out.write("               <i class=\"fa fa-refresh\" style=\"font-size: 24px\"></i> 새로고침\r\n");
      out.write("            </button> -->\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"table-wrapper\"\r\n");
      out.write("            style=\"width: 35%; float: left; margin-left: 40px;\">\r\n");
      out.write("            <a href=\"https://www.bithumb.com/\" class=\"logo\"><img\r\n");
      out.write("               src=\"images/logo_bithumb.png\" width=\"240\" height=\"66\" /></a> <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <table class=\"alt\">\r\n");
      out.write("               <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>Coin</th>\r\n");
      out.write("                     <th>Price(원화: KRW) <div style=\"float:right;\">24시간 변동률</div></th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </thead>\r\n");
      out.write("               <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">비트코인(BTC)</td>\r\n");
      out.write("                     <td><div id=\"BTC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">이더리움(ETH)</td>\r\n");
      out.write("                     <td><div id=\"ETH\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">대쉬 코인(DASH)</td>\r\n");
      out.write("                     <td><div id=\"DASH\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">라이트 코인(LTC)</td>\r\n");
      out.write("                     <td><div id=\"LTC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">이더리움 클래식(ETC)</td>\r\n");
      out.write("                     <td><div id=\"ETC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">리플(XRP)</td>\r\n");
      out.write("                     <td><div id=\"XRP\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"table-wrapper\"   style=\"width: 20%; float: left; margin:0 35px;\">\r\n");
      out.write("            <h4 style=\"margin-bottom:37px; text-align:center; color:#959ab3;\"> [ 오늘의 환율 ] <br>\r\n");
      out.write("            \t\t\t\t\t\t\t1KRW/USD : <span id=\"krw\"></span> </h4>\r\n");
      out.write("            <table class=\"alt\">\r\n");
      out.write("               <thead>\r\n");
      out.write("                  <th style=\"text-align:center;\"><strong>국내외 시세차이(%)</strong></th>\r\n");
      out.write("               </thead>\r\n");
      out.write("               <tbody style=\"text-align:center;\">\r\n");
      out.write("                  <tr> \r\n");
      out.write("                     <td><div id=\"BTC_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td><div id=\"ETH_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td><div id=\"DASH_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td><div id=\"LTC_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td><div id=\"ETC_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td><div id=\"XRP_p\" style=\"text-align:center; height:30px;\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </tbody>\r\n");
      out.write("               <!-- <tfoot>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td colspan=\"2\"></td>\r\n");
      out.write("                     <td>100.00</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </tfoot> -->\r\n");
      out.write("            </table>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div class=\"table-wrapper\"\r\n");
      out.write("            style=\"width: 35%; float: right; margin-right: 40px;\">\r\n");
      out.write("            <a href=\"https://poloniex.com/\" class=\"logo\"><img\r\n");
      out.write("               src=\"images/poloniex.png\" width=\"250\" height=\"40\"\r\n");
      out.write("               style=\"margin-top: 24px;\" /></a>  <br> <br>\r\n");
      out.write("            <table class=\"alt\">\r\n");
      out.write("               <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>Coin</th>\r\n");
      out.write("                     <th>Price(원화: KRW) <div style=\"float:right;\">24시간 변동률</div></th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </thead>\r\n");
      out.write("               <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">비트코인(BTC)</td>\r\n");
      out.write("                     <td><div id=\"PBTC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">이더리움(ETH)</td>\r\n");
      out.write("                     <td><div id=\"PETH\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">대쉬 코인(DASH)</td>\r\n");
      out.write("                     <td><div id=\"PDASH\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">라이트 코인(LTC)</td>\r\n");
      out.write("                     <td><div id=\"PLTC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">이더리움 클래식(ETC)</td>\r\n");
      out.write("                     <td><div id=\"PETC\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"text-align:left;\">리플(XRP)</td>\r\n");
      out.write("                     <td><div id=\"PXRP\"><i class=\"fa fa-spinner fa-spin\" style=\"font-size:24px\"></i></div></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div style=\"width: 16%; margin: 0 auto; margin-bottom: 20px;\">\r\n");
      out.write("         <a href=\"#one\" class=\"button next scrolly\">코인 별 상세보기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Main -->\r\n");
      out.write("      <div id=\"main\">\r\n");
      out.write("         <!-- One -->\r\n");
      out.write("         <section id=\"one\" class=\"tiles\">\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic01.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/eth.png\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=eth\" class=\"link\">ETH</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>이더리움</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic02.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/btc.png\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=btc\" class=\"link\">BTC</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>비트코인</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic03.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/dash.png\" width=\"100\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=dash\" class=\"link\">DASH</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>대쉬코인</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic04.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/ltc.png\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=ltc\" class=\"link\">LTC</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>라이트코인</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic05.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/etc.png\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=etc\" class=\"link\">ETC</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>이더리움 클래식</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article>\r\n");
      out.write("               <span class=\"image\"> <!-- <img src=\"images/pic06.jpg\" alt=\"\" /> -->\r\n");
      out.write("                  <img src=\"images/xrp.png\" />\r\n");
      out.write("               </span>\r\n");
      out.write("               <header class=\"major\">\r\n");
      out.write("                  <h3>\r\n");
      out.write("                     <a href=\"coin?command=xrp\" class=\"link\">XRP</a>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <p>리플</p>\r\n");
      out.write("               </header>\r\n");
      out.write("            </article>\r\n");
      out.write("         </section>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Footer -->\r\n");
      out.write("      <footer id=\"footer\">\r\n");
      out.write("         <div class=\"inner\"\r\n");
      out.write("            style=\"padding: 10px !important; text-align: center; width: 60%;\">\r\n");
      out.write("            <br>\r\n");
      out.write("            <ul class=\"copyright\">\r\n");
      out.write("               <li>ⓒ 2017. kData coInsight Team all rights reserved.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Scripts -->\r\n");
      out.write("   <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/skel.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("   <!--[if lte IE 8]><script src=\"assets/js/ie/respond.min.js\"></script><![endif]-->\r\n");
      out.write("   <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(235,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.member}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <p>\r\n");
          out.write("                  <a href=\"join.jsp\">JOIN</a>\r\n");
          out.write("               </p>\r\n");
          out.write("               <p>\r\n");
          out.write("                  <a href=\"login.jsp\">LOGIN</a>\r\n");
          out.write("               </p>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(243,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.member}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</p>\r\n");
          out.write("               <p>\r\n");
          out.write("                  <a href=\"coin?command=logout\">logout</a>\r\n");
          out.write("               </p>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /index.jsp(263,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.member}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"login.jsp\" class=\"button special fit\">Log In</a></li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /index.jsp(266,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.member}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li><a href=\"coin?command=logout\" class=\"button special fit\">Log\r\n");
          out.write("\t\t\t\t\t\t\tOut</a></li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
